remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Halls of Torment Builder]
description: [This website is a Halls of Torment build creator and enables players to share their builds with others]